/**
 * Extra Birth Collection shots for the product pages.
 *
 * `birthgal-*` are the white studio plates. `blbirth-*` are the designer's own
 * photographs — the set on a real pet, on a model, and the collar on white.
 *
 * Selected from contact sheets of all 182 archive images. Excluded: anything
 * with a Chinese month/stone headline, the component-breakdown diagrams, the
 * bilingual "Locket Open" cards, and two frames carrying an "AI 生成"
 * watermark. The plate still leads each gallery.
 *
 * Generated by scratchpad/apply_birth_gallery.py; edit there, not here.
 */
export const birthGallery: Record<string, string[]> = {
  "april-peach-moonstone": ["/art/birthgal-april-peach-moonstone-0.jpg", "/art/birthgal-april-peach-moonstone-1.jpg", "/art/birthgal-april-peach-moonstone-2.jpg", "/art/blbirth-april-peach-moonstone-1.jpg", "/art/blbirth-april-peach-moonstone-2.jpg", "/art/blbirth-april-peach-moonstone-3.jpg", "/art/blbirth-april-peach-moonstone-4.jpg"],
  "august-tigers-eye": ["/art/birthgal-august-tigers-eye-0.jpg", "/art/birthgal-august-tigers-eye-1.jpg", "/art/birthgal-august-tigers-eye-2.jpg", "/art/blbirth-august-tigers-eye-1.jpg", "/art/blbirth-august-tigers-eye-2.jpg", "/art/blbirth-august-tigers-eye-3.jpg", "/art/blbirth-august-tigers-eye-4.jpg"],
  "december-obsidian": ["/art/birthgal-december-obsidian-0.jpg", "/art/birthgal-december-obsidian-1.jpg", "/art/birthgal-december-obsidian-2.jpg", "/art/blbirth-december-obsidian-1.jpg", "/art/blbirth-december-obsidian-2.jpg", "/art/blbirth-december-obsidian-3.jpg", "/art/blbirth-december-obsidian-4.jpg"],
  "february-amethyst": ["/art/birthgal-february-amethyst-0.jpg", "/art/birthgal-february-amethyst-1.jpg", "/art/birthgal-february-amethyst-2.jpg", "/art/blbirth-february-amethyst-1.jpg", "/art/blbirth-february-amethyst-2.jpg", "/art/blbirth-february-amethyst-3.jpg", "/art/blbirth-february-amethyst-4.jpg"],
  "january-red-agate": ["/art/birthgal-january-red-agate-0.jpg", "/art/birthgal-january-red-agate-1.jpg", "/art/birthgal-january-red-agate-2.jpg", "/art/blbirth-january-red-agate-1.jpg", "/art/blbirth-january-red-agate-2.jpg", "/art/blbirth-january-red-agate-3.jpg", "/art/blbirth-january-red-agate-4.jpg"],
  "july-rose-quartz": ["/art/birthgal-july-rose-quartz-0.jpg", "/art/birthgal-july-rose-quartz-1.jpg", "/art/birthgal-july-rose-quartz-2.jpg", "/art/blbirth-july-rose-quartz-1.jpg", "/art/blbirth-july-rose-quartz-2.jpg", "/art/blbirth-july-rose-quartz-3.jpg", "/art/blbirth-july-rose-quartz-4.jpg"],
  "june-clear-quartz": ["/art/birthgal-june-clear-quartz-0.jpg", "/art/birthgal-june-clear-quartz-1.jpg", "/art/birthgal-june-clear-quartz-2.jpg", "/art/blbirth-june-clear-quartz-1.jpg", "/art/blbirth-june-clear-quartz-2.jpg", "/art/blbirth-june-clear-quartz-3.jpg", "/art/blbirth-june-clear-quartz-4.jpg"],
  "march-amazonite": ["/art/birthgal-march-amazonite-0.jpg", "/art/birthgal-march-amazonite-1.jpg", "/art/birthgal-march-amazonite-2.jpg", "/art/blbirth-march-amazonite-1.jpg", "/art/blbirth-march-amazonite-2.jpg", "/art/blbirth-march-amazonite-3.jpg", "/art/blbirth-march-amazonite-4.jpg"],
  "may-lapis-lazuli": ["/art/birthgal-may-lapis-lazuli-0.jpg", "/art/birthgal-may-lapis-lazuli-1.jpg", "/art/birthgal-may-lapis-lazuli-2.jpg", "/art/blbirth-may-lapis-lazuli-1.jpg", "/art/blbirth-may-lapis-lazuli-2.jpg", "/art/blbirth-may-lapis-lazuli-3.jpg", "/art/blbirth-may-lapis-lazuli-4.jpg"],
  "november-citrine": ["/art/birthgal-november-citrine-0.jpg", "/art/birthgal-november-citrine-1.jpg", "/art/birthgal-november-citrine-2.jpg", "/art/blbirth-november-citrine-1.jpg", "/art/blbirth-november-citrine-2.jpg", "/art/blbirth-november-citrine-3.jpg", "/art/blbirth-november-citrine-4.jpg"],
  "october-grey-moonstone": ["/art/birthgal-october-grey-moonstone-0.jpg", "/art/birthgal-october-grey-moonstone-1.jpg", "/art/birthgal-october-grey-moonstone-2.jpg", "/art/blbirth-october-grey-moonstone-1.jpg", "/art/blbirth-october-grey-moonstone-2.jpg", "/art/blbirth-october-grey-moonstone-3.jpg", "/art/blbirth-october-grey-moonstone-4.jpg"],
  "september-strawberry-quartz": ["/art/birthgal-september-strawberry-quartz-0.jpg", "/art/birthgal-september-strawberry-quartz-1.jpg", "/art/birthgal-september-strawberry-quartz-2.jpg", "/art/blbirth-september-strawberry-quartz-1.jpg", "/art/blbirth-september-strawberry-quartz-2.jpg", "/art/blbirth-september-strawberry-quartz-3.jpg", "/art/blbirth-september-strawberry-quartz-4.jpg"],
};
