/**
 * Which two photographs a collection card shows.
 *
 * `front` is the animal wearing the collar charm — the proposition, not the
 * product. `hover` is the owner wearing the bracelet, so one pass of the
 * cursor tells the whole "one for you, one for them" story without a click.
 *
 * Both come from the curated designer set; the kinds were assigned during the
 * photo review (worn-by-pet / scale / detail). Falls back to the old worn-
 * shot or the studio plate where a design lacks one.
 *
 * Generated by scratchpad/build_card_shots.py; edit there, not here.
 */
export const cardShots: Record<string, { front: string; hover: string }> = {
  "amethyst-clarity": { front: "/art/bl-amethyst-clarity-3.jpg", hover: "/art/bl-amethyst-clarity-2.jpg" },
  "amethyst-serenity": { front: "/art/bl-amethyst-serenity-2.jpg", hover: "/art/bl-amethyst-serenity-1.jpg" },
  "azure-lagoon": { front: "/art/bl-azure-lagoon-3.jpg", hover: "/art/bl-azure-lagoon-1.jpg" },
  "crimson-fortune": { front: "/art/bl-crimson-fortune-2.jpg", hover: "/art/bl-crimson-fortune-1.jpg" },
  "frosted-crystal": { front: "/art/bl-frosted-crystal-2.jpg", hover: "/art/bl-frosted-crystal-1.jpg" },
  "monets-garden": { front: "/art/bl-monets-garden-2.jpg", hover: "/art/bl-monets-garden-1.jpg" },
  "rainbow-spirit": { front: "/art/bl-rainbow-spirit-2.jpg", hover: "/art/bl-rainbow-spirit-3.jpg" },
  "rose-heart": { front: "/art/bl-rose-heart-2.jpg", hover: "/art/bl-rose-heart-1.jpg" },
  "rose-latte": { front: "/art/bl-rose-latte-2.jpg", hover: "/art/bl-rose-latte-1.jpg" },
  "starfall-galaxy": { front: "/art/bl-starfall-galaxy-2.jpg", hover: "/art/bl-starfall-galaxy-1.jpg" },
  "stone-path": { front: "/art/bl-stone-path-2.jpg", hover: "/art/bl-stone-path-1.jpg" },
  "tigers-vigil": { front: "/art/bl-tigers-vigil-2.jpg", hover: "/art/bl-tigers-vigil-1.jpg" },
  "evil-eye-ward": { front: "/art/bl-evil-eye-ward-2.jpg", hover: "/art/bl-evil-eye-ward-1.jpg" },
  "fluorite-mist": { front: "/art/bl-fluorite-mist-2.jpg", hover: "/art/bl-fluorite-mist-1.jpg" },
  "chakra-wheel": { front: "/art/bl-chakra-wheel-2.jpg", hover: "/art/bl-chakra-wheel-1.jpg" },
  "pearl-dusk": { front: "/art/bl-pearl-dusk-2.jpg", hover: "/art/bl-pearl-dusk-1.jpg" },
  "carnelian-ember": { front: "/art/bl-carnelian-ember-2.jpg", hover: "/art/bl-carnelian-ember-1.jpg" },
  "aventurine-glade": { front: "/art/bl-aventurine-glade-2.jpg", hover: "/art/bl-aventurine-glade-1.jpg" },
};
