/**
 * Extra Everyday Collar shots for the product pages.
 *
 * The front (cat wearing) and hover (collar alone) shots are derived from the
 * id, so only the remaining gallery frames are listed here.
 *
 * Generated by scratchpad/apply_everyday.py; edit there, not here.
 */
export const everydayGallery: Record<string, string[]> = {
  "everyday-amazonite": ["/art/ev-everyday-amazonite-1.jpg", "/art/ev-everyday-amazonite-2.jpg", "/art/ev-everyday-amazonite-3.jpg"],
  "everyday-xiuyan-jade": ["/art/ev-everyday-xiuyan-jade-1.jpg", "/art/ev-everyday-xiuyan-jade-2.jpg", "/art/ev-everyday-xiuyan-jade-3.jpg"],
  "everyday-rose-quartz": ["/art/ev-everyday-rose-quartz-1.jpg", "/art/ev-everyday-rose-quartz-2.jpg", "/art/ev-everyday-rose-quartz-3.jpg"],
  "everyday-amethyst": ["/art/ev-everyday-amethyst-1.jpg", "/art/ev-everyday-amethyst-2.jpg", "/art/ev-everyday-amethyst-3.jpg"],
  "everyday-tigers-eye": ["/art/ev-everyday-tigers-eye-1.jpg", "/art/ev-everyday-tigers-eye-2.jpg", "/art/ev-everyday-tigers-eye-3.jpg"],
};
