/**
 * Extra product-page shots, beyond the listing tile and the worn photograph.
 *
 * The `gallery-*` files are the white studio plates. The `bl-*` files are the
 * designer's own photographs, kept because they show what a plate cannot: the
 * piece in a hand or on a wrist, so a buyer can read the bead size.
 *
 * Order matters. The listing plate leads, the remaining plates follow, and the
 * designer's shots come after them — leading with a styled backdrop made the
 * page read as a different product from the tile that linked to it.
 *
 * Generated by scratchpad/apply_bl_gallery.py; edit there, not here.
 */
export const galleryShots: Record<string, string[]> = {
  "amethyst-clarity": ["/art/gallery-amethyst-clarity-1.jpg", "/art/gallery-amethyst-clarity-2.jpg", "/art/bl-amethyst-clarity-1.jpg", "/art/bl-amethyst-clarity-2.jpg", "/art/bl-amethyst-clarity-3.jpg", "/art/bl-amethyst-clarity-4.jpg"],
  "amethyst-serenity": ["/art/gallery-amethyst-serenity-1.jpg", "/art/gallery-amethyst-serenity-2.jpg", "/art/bl-amethyst-serenity-1.jpg", "/art/bl-amethyst-serenity-2.jpg", "/art/bl-amethyst-serenity-3.jpg", "/art/bl-amethyst-serenity-4.jpg"],
  "azure-lagoon": ["/art/gallery-azure-lagoon-1.jpg", "/art/bl-azure-lagoon-1.jpg", "/art/bl-azure-lagoon-2.jpg", "/art/bl-azure-lagoon-3.jpg", "/art/bl-azure-lagoon-4.jpg"],
  "crimson-fortune": ["/art/gallery-crimson-fortune-1.jpg", "/art/gallery-crimson-fortune-2.jpg", "/art/bl-crimson-fortune-1.jpg", "/art/bl-crimson-fortune-2.jpg", "/art/bl-crimson-fortune-3.jpg", "/art/bl-crimson-fortune-4.jpg"],
  "frosted-crystal": ["/art/gallery-frosted-crystal-1.jpg", "/art/gallery-frosted-crystal-2.jpg", "/art/bl-frosted-crystal-1.jpg", "/art/bl-frosted-crystal-2.jpg", "/art/bl-frosted-crystal-3.jpg", "/art/bl-frosted-crystal-4.jpg"],
  "monets-garden": ["/art/gallery-monets-garden-1.jpg", "/art/gallery-monets-garden-2.jpg", "/art/bl-monets-garden-1.jpg", "/art/bl-monets-garden-2.jpg", "/art/bl-monets-garden-3.jpg", "/art/bl-monets-garden-4.jpg"],
  "rainbow-spirit": ["/art/gallery-rainbow-spirit-1.jpg", "/art/gallery-rainbow-spirit-2.jpg", "/art/bl-rainbow-spirit-1.jpg", "/art/bl-rainbow-spirit-2.jpg", "/art/bl-rainbow-spirit-3.jpg", "/art/bl-rainbow-spirit-4.jpg"],
  "rose-heart": ["/art/gallery-rose-heart-1.jpg", "/art/gallery-rose-heart-2.jpg", "/art/bl-rose-heart-1.jpg", "/art/bl-rose-heart-2.jpg", "/art/bl-rose-heart-3.jpg", "/art/bl-rose-heart-4.jpg"],
  "rose-latte": ["/art/gallery-rose-latte-1.jpg", "/art/bl-rose-latte-1.jpg", "/art/bl-rose-latte-2.jpg", "/art/bl-rose-latte-3.jpg", "/art/bl-rose-latte-4.jpg"],
  "starfall-galaxy": ["/art/gallery-starfall-galaxy-1.jpg", "/art/gallery-starfall-galaxy-2.jpg", "/art/bl-starfall-galaxy-1.jpg", "/art/bl-starfall-galaxy-2.jpg", "/art/bl-starfall-galaxy-3.jpg", "/art/bl-starfall-galaxy-4.jpg"],
  "stone-path": ["/art/gallery-stone-path-1.jpg", "/art/gallery-stone-path-2.jpg", "/art/bl-stone-path-1.jpg", "/art/bl-stone-path-2.jpg", "/art/bl-stone-path-3.jpg", "/art/bl-stone-path-4.jpg"],
  "tigers-vigil": ["/art/gallery-tigers-vigil-1.jpg", "/art/gallery-tigers-vigil-2.jpg", "/art/bl-tigers-vigil-1.jpg", "/art/bl-tigers-vigil-2.jpg", "/art/bl-tigers-vigil-3.jpg", "/art/bl-tigers-vigil-4.jpg"],
};
