/**
 * Stripe price IDs, one per design per variant.
 *
 * Generated by `scripts/stripe-sync.mjs` — run it with your own secret key and
 * it rewrites this file. An empty string means that variant has not been
 * created in Stripe yet; the checkout route treats it as unavailable rather
 * than sending a broken session to Stripe.
 */
import type { VariantKey } from "./variants";

export type PriceMap = Record<string, Partial<Record<VariantKey, string>>>;

export const stripePrices: PriceMap = {};

export function priceIdFor(productId: string, variant: VariantKey): string | null {
  return stripePrices[productId]?.[variant] || null;
}

/** The variants that currently have a Stripe price for this design. */
export function availableVariants(productId: string): VariantKey[] {
  const row = stripePrices[productId] ?? {};
  return (Object.keys(row) as VariantKey[]).filter((k) => !!row[k]);
}
