/**
 * Stripe price IDs, one per design per variant.
 *
 * GENERATED by scripts/stripe-sync.mjs — do not edit by hand. Re-run the
 * script after any price change. An empty string means that variant has not
 * been created in Stripe yet; the checkout route treats it as unavailable
 * rather than sending a broken session to Stripe.
 */
import type { VariantKey } from "./variants";

export type PriceMap = Record<string, Partial<Record<VariantKey, string>>>;

export const stripePrices: PriceMap = {
  "rainbow-spirit": {
    "pet": "price_1TzAe94JAWFfqt5JoliCAooG",
    "owner": "price_1TzAeA4JAWFfqt5JfW28lTaL",
    "set": "price_1TzAeB4JAWFfqt5Jkst30Hby"
  },
  "amethyst-serenity": {
    "pet": "price_1TzAeC4JAWFfqt5Jltfa5dTp",
    "owner": "price_1TzAeD4JAWFfqt5JAN2eStte",
    "set": "price_1TzAeD4JAWFfqt5JUahZ6pWc"
  },
  "starfall-galaxy": {
    "pet": "price_1TzAeE4JAWFfqt5JL6Ab6l0f",
    "owner": "price_1TzAeF4JAWFfqt5JwA9JexRU",
    "set": "price_1TzAeG4JAWFfqt5J7U5Eg8OH"
  },
  "azure-lagoon": {
    "pet": "price_1TzAeH4JAWFfqt5JgdMaA85L",
    "owner": "price_1TzAeH4JAWFfqt5JkUa1BnOm",
    "set": "price_1TzAeI4JAWFfqt5Jf7xipft9"
  },
  "crimson-fortune": {
    "pet": "price_1TzAeJ4JAWFfqt5Jco5FllCA",
    "owner": "price_1TzAeK4JAWFfqt5JyW6Bo4uI",
    "set": "price_1TzAeL4JAWFfqt5JtZMEAr5h"
  },
  "tigers-vigil": {
    "pet": "price_1TzAeM4JAWFfqt5J3FcqDOcP",
    "owner": "price_1TzAeN4JAWFfqt5JgIXIopTG",
    "set": "price_1TzAeN4JAWFfqt5JpI19fgKL"
  },
  "frosted-crystal": {
    "pet": "price_1TzAeP4JAWFfqt5J5ZcDKBvg",
    "owner": "price_1TzAeP4JAWFfqt5JKLu4pUro",
    "set": "price_1TzAeQ4JAWFfqt5JuzMg5At6"
  },
  "rose-heart": {
    "pet": "price_1TzAeR4JAWFfqt5JouVmLxlu",
    "owner": "price_1TzAeS4JAWFfqt5Jsms1CFnF",
    "set": "price_1TzAeS4JAWFfqt5JeGvZWHpN"
  },
  "monets-garden": {
    "pet": "price_1TzAeU4JAWFfqt5JnkwMh2wA",
    "owner": "price_1TzAeU4JAWFfqt5JshM02K8L",
    "set": "price_1TzAeV4JAWFfqt5JdafxvOqv"
  },
  "stone-path": {
    "pet": "price_1TzAeX4JAWFfqt5JGVUb3CMB",
    "owner": "price_1TzAeX4JAWFfqt5J47sqCA2X",
    "set": "price_1TzAeY4JAWFfqt5Jlyz1ZbCo"
  },
  "amethyst-clarity": {
    "pet": "price_1TzAeZ4JAWFfqt5JNsn1acyX",
    "owner": "price_1TzAea4JAWFfqt5Jp4IPc4kD",
    "set": "price_1TzAea4JAWFfqt5JWoYgrV09"
  },
  "rose-latte": {
    "pet": "price_1TzAec4JAWFfqt5JcNMuRnvP",
    "owner": "price_1TzAec4JAWFfqt5Ju085yP2Q",
    "set": "price_1TzAed4JAWFfqt5JihFUEVOs"
  },
  "january-red-agate": {
    "pet": "price_1TzAee4JAWFfqt5J9dwxNQxO",
    "owner": "price_1TzAef4JAWFfqt5JIHEiI1e1",
    "set": "price_1TzAeg4JAWFfqt5JMWy3ryjL"
  },
  "february-amethyst": {
    "pet": "price_1TzAeh4JAWFfqt5Jhqyx9zNF",
    "owner": "price_1TzAei4JAWFfqt5JHoxsTVSa",
    "set": "price_1TzAei4JAWFfqt5JDudfmjqs"
  },
  "march-amazonite": {
    "pet": "price_1TzAej4JAWFfqt5JLXogPUWT",
    "owner": "price_1TzAek4JAWFfqt5Jb9xXv1aU",
    "set": "price_1TzAel4JAWFfqt5J2ktor7di"
  },
  "april-peach-moonstone": {
    "pet": "price_1TzAem4JAWFfqt5J7dOkXvNB",
    "owner": "price_1TzAen4JAWFfqt5J44eXmGwQ",
    "set": "price_1TzAen4JAWFfqt5Jb70LCZl0"
  },
  "may-lapis-lazuli": {
    "pet": "price_1TzAep4JAWFfqt5JuEd0Mtw0",
    "owner": "price_1TzAep4JAWFfqt5Jx4WbJSuB",
    "set": "price_1TzAeq4JAWFfqt5Jh4V3cdZ8"
  },
  "june-clear-quartz": {
    "pet": "price_1TzAes4JAWFfqt5J18j5tOJQ",
    "owner": "price_1TzAes4JAWFfqt5JZOedmtWh",
    "set": "price_1TzAet4JAWFfqt5J7ZZDdjIN"
  },
  "july-rose-quartz": {
    "pet": "price_1TzAeu4JAWFfqt5JcnttK0fp",
    "owner": "price_1TzAev4JAWFfqt5JhAKVKl70",
    "set": "price_1TzAev4JAWFfqt5J3EVYu2CR"
  },
  "august-tigers-eye": {
    "pet": "price_1TzAex4JAWFfqt5JnwZaYPU5",
    "owner": "price_1TzAex4JAWFfqt5Jp36kOeHE",
    "set": "price_1TzAey4JAWFfqt5JimFX1jzf"
  },
  "september-strawberry-quartz": {
    "pet": "price_1TzAf04JAWFfqt5J5GYOsq1x",
    "owner": "price_1TzAf04JAWFfqt5JIrGZsm5K",
    "set": "price_1TzAf14JAWFfqt5J3ux0tNt7"
  },
  "october-grey-moonstone": {
    "pet": "price_1TzAf24JAWFfqt5Joe2wFSNB",
    "owner": "price_1TzAf34JAWFfqt5JuDzjmZ6E",
    "set": "price_1TzAf34JAWFfqt5JrbzonrqK"
  },
  "november-citrine": {
    "pet": "price_1TzAf54JAWFfqt5Jnr1qitKC",
    "owner": "price_1TzAf54JAWFfqt5J3uTpjDQP",
    "set": "price_1TzAf64JAWFfqt5J7JhzufQs"
  },
  "december-obsidian": {
    "pet": "price_1TzAf84JAWFfqt5J0uuDBHHP",
    "owner": "price_1TzAf84JAWFfqt5J7erBYg6C",
    "set": "price_1TzAf94JAWFfqt5Jwe8ktWP4"
  },
  "everyday-amazonite": {
    "pet": "price_1TzDbJ4JAWFfqt5JsyyU0ZMX"
  },
  "everyday-xiuyan-jade": {
    "pet": "price_1TzDbK4JAWFfqt5JuIF59n9t"
  },
  "everyday-rose-quartz": {
    "pet": "price_1TzDbL4JAWFfqt5JriPdD1zt"
  },
  "everyday-amethyst": {
    "pet": "price_1TzDbN4JAWFfqt5JWw2H9dJH"
  },
  "everyday-tigers-eye": {
    "pet": "price_1TzDbO4JAWFfqt5JmVDdtMFf"
  }
};

export function priceIdFor(productId: string, variant: VariantKey): string | null {
  return stripePrices[productId]?.[variant] || null;
}

/** The variants that currently have a Stripe price for this design. */
export function availableVariants(productId: string): VariantKey[] {
  const row = stripePrices[productId] ?? {};
  return (Object.keys(row) as VariantKey[]).filter((k) => !!row[k]);
}
